//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;

    public partial class EduProg
    {
        public int EProgID { get; set; }
        public int UserID { get; set; }
		public string CourseID { get; set; }
		public string FacultyID { get; set; }
        public byte Semester { get; set; }
		public string SubjectID { get; set; }
		public float TotalMark { get; set; }
		public bool Success { get; set; }
	}
}
