//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
	using System;
	using System.Data;

	public partial class Faculty
	{
		public string FacultyID { get; set; }
		public string FacultyName { get; set; }
		public DateTime FoundingDate { get; set; }
		public string Description { get; set; }

		public Faculty()
		{

		}

		public Faculty(DataRow row)
		{
			FacultyID = row["FacultyID"].ToString();
			FacultyName = row["FacultyName"].ToString();
			FoundingDate = Convert.ToDateTime(row["FoundingDate"]);
			Description = row["Description"].ToString();
		}
	}
}
