//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
	using System;
	using System.Collections.Generic;
	using System.Data;

	public partial class Question
    {
		public string QuestionIdx { get; set; }
		public int QuestionID { get; set; }
        public string ExamID { get; set; }
        public string SubjectID { get; set; }
		public string QContent { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string Answer { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }

		public Question()
		{
        }

		public Question(DataRow row)
        {
            QuestionID = int.Parse(row["QuestionID"].ToString());
            ExamID = row["ExamID"].ToString();
            SubjectID = row["SubjectID"].ToString();
            QContent = row["QContent"].ToString();
            OptionA = row["OptionA"].ToString();
            OptionB = row["OptionB"].ToString();
            OptionC = row["OptionC"].ToString();
            OptionD = row["OptionD"].ToString();
            Answer = row["Answer"].ToString();
        }
    }
}
