//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
	using System;
	using System.Data;

	public partial class Subject
    {
        public string SubjectID { get; set; }
		public string SubjectRole { get; set; }
		public string CourseID { get; set; }
		public string FacultyID { get; set; }
		public byte SemesterID { get; set; }
		public string SubjectName { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }

		public Subject()
		{

		}
		public Subject(DataRow row)
		{
            SubjectID = row["SubjectID"].ToString();
			SubjectRole = row["SubjectRole"].ToString();
			CourseID = row["CourseID"].ToString();
			FacultyID = row["FacultyID"].ToString();
			SemesterID = byte.Parse(row["SemesterID"].ToString());
            SubjectName = row["SubjectName"].ToString();
		}
    }
}
