//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;

    public partial class TrainingRole
    {
        public string TrainingID { get; set; }
        public string TrainingName { get; set; }
        public string Description { get; set; }
    }
}
