//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;

    public partial class UserClass
    {
        public string ClassID { get; set; }
        public string CourseID { get; set; }
        public string FacultyID { get; set; }
        public int AdmissionYear { get; set; }
		public byte NofTrainingSemester { get; set; }
		public string Description { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}
